<!DOCTYPE html>
<html>
<head>
	<title> MyTodos </title>
	<link rel="stylesheet" type="text/css" href="./assets/css/bootstrap.min.css" />
	<script type="text/javascript" src="./assets/js/jquery-3.2.1.min.js"></script>
	<script type="text/javascript" src="./assets/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">MyTodos</a>
        </div>
        <form class="navbar-form navbar-right" role="search">
            <a href="./add.php" class="btn btn-default">
                <span class="glyphicon glyphicon-plus-sign"></span>
                Add Task
            </a>
        </form>
    </div>
</nav>

<div class="container">
	<?php $this->content() ?>
</div>

</body>
</html>