<?php $todo = $this->todo; ?>
<h2>Edit Task</h2>
<form action="/tasks/edit?id=<?=$_GET['id']?>" method="POST">
	<label>
		Title: <input type="text" name="title" value="<?=$todo['title'];?>" />
	</label>
	<br />
	<label>
		Text:
		<br />
		<textarea name="body" cols="50" rows="20"><?=$todo['body']?></textarea>
	</label>
	<br />
	<input type="hidden" name="id" value="<?=$todo['id'];?>" />
	<input type="submit" value="Edit Task" />
</form>