<?php
	$todos = $this->todos;
	foreach ($todos as $todo) {
		if($todo['status'] != 2) {
?>

<section>
	<div class="row">
		<div class="col-xs-12">
			<h3 class="<?= $todo['status'] == 0 ? 'text-warning' : 'text-success' ?>"><?=$todo['title']?>
			<span class="small">
				<?= $todo['status'] == 0 ? '<span class="glyphicon glyphicon-remove text-warning"></span>' : '<span class="glyphicon glyphicon-ok text-success"></span>' ?>
				<form action="/toggle" method="POST">
					<button class="btn btn-primary pull-right">Toggle</button>
					<input type="hidden" name="id" value="<?=$todo['id']?>" />
				</form>
			</span>
			</h3>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-8">
			<p><?=nl2br($todo['body'])?></p>
		</div>
		<div class="col-xs-4">
			<p class="pull-right">
				<a class='btn btn-warning' href='/edit?id=<?=$todo["id"]?>'>Edit</a>
				<a class='btn btn-danger' href='/delete?id=<?=$todo["id"]?>'>Delete</a>
			</p>

		</div>
	</div>
</section>

<?php
		}
	}
?>